---
antora:
  name: modules
  dir: www
  modules:
    - name: "module-01"
      label: "Overview"
      solveButton: false
    - name: "module-02"
      label: "CVEs"
      solveButton: false
    - name: "module-03"
      label: "Malware"
      solveButton: false
    - name: "module-04"
      label: "Lightspeed Advisor in Satellite"
      solveButton: false
    - name: "module-05"
      label: "Conclusion"
      solveButton: false

tabs:
  - name: "Satellite Web UI"
    url: https://satellite-${guid}.${domain}/
  - name: "satellite.lab terminal"
    url: /wetty_satellite/ssh/root
  - name: "rhel-${guid}-1.lab terminal"
    url: /wetty_rhel-${guid}-1/ssh/root
  - name: "rhel-${guid}-2.lab terminal"
    url: /wetty_rhel-${guid}-2/ssh/root
  - name: "rhel-${guid}-3.lab terminal"
    url: /wetty_rhel-${guid}-3/ssh/root